const ProjectData = {
    frenchteacher: {
      image: '/assets/images/frenchteacher.jpg',
      title: 'AI French Teacher',
      tagline: "World's most patient language partner",
      slug: 'frenchteacher',
      github: 'https://github.com/Janecching',
      website: 'https://github.com/Janecching',
      skill: ['JavaScript', 'Node', 'OpenAI', 'AI/ML', 'Full-stack'],
      overview: "Language learning web app that enhances conversation skills through simulated scenarios and offers sentence translation and correction for practice.",
      screens: '/assets/images/frenchteacher.jpg',
      tech:`Web development (React, Next, Node, Express, OpenAI), UI/UX design, API integration, prompt engineering, language learning principles`, 
    },
    gooddays: {
      image: '/assets/images/gooddays.gif',
      title: 'Good Days',
      tagline: 'GPT powered journal that turns braindump into structured list, learn what makes your day a good day',
      slug: 'gooddays',
      github: 'https://github.com/Janecching/one-day',
      website: 'https://one-hymvp2nzb-janecching.vercel.app/',
      skill: ['React', 'JavaScript', 'Node', 'OpenAI', 'AI/ML', 'Full-stack'],
      overview: `Existing features:
      - Turns unstructured thoughts into a daily schedule using the OpenAI API.\n
      - Allows users to easily drag and check off tasks on their daily schedule.\n
      - Enables users to record journal entries, add pictures, and rate their day.\n
      Upcoming features:\n
      - Analyzes journal entries and day ratings to suggest activities that contribute to a "good day".\n
      - Monthly calendar view that displays uploaded pictures, encouraging users to maintain streaks.\n`,
      screens: '/assets/images/gooddays.gif',
      tech:`Web development (React, Next, Node.js, Express, OpenAI), UI/UX design, API integration, natural language processing`, 
    },
    discoveryqueue: {
      image: '/assets/images/dq.gif',
      title: 'Discovery Queue',
      tagline: "Song recommender based on analyzing user's favourite songs",
      slug: 'discoveryqueue',
      github: 'https://discoverq-83c0b.web.app/',
      website: 'https://discoverq-83c0b.web.app/',
      skill: ['React', 'Node', 'AWS', 'Python', 'AI/ML', 'Full-stack'],
      overview: "Search new songs via a buzzfeed style quiz, filtering for music attributes, and most similar song based on cosine similarity",
      screens: '/assets/images/dq.gif',
      tech:`Databases`, 
    },
    virtualcampus: {
      image: '/assets/images/virtualcampus.gif',
      title: 'Virtual Campus',
      tagline: 'Real-time multiplayer game for my masters program and community board',
      slug: 'virtualcampus',
      github: 'https://devpost.com/software/virtual-campus-1ra9fq',
      website: 'https://school-18507.web.app/social.html',
      skill: ['React', 'JavaScript', 'GCP', 'Front-end'],
      overview: "This is a virtual campus made for my masters program community. It consists of a campus ground with live chat view and a focus room with pomodoro timer",
      screens: '/assets/images/virtualcampus.gif',
      tech:`Javascript, real time multiplayer game`, 
    },
    greenfridge: {
      image: '/assets/images/greenfridge.jpg',
      title: 'Green Fridge',
      tagline: 'Fridge camera and accompanying app',
      slug: 'greenfridge',
      github: 'https://devpost.com/software/greenfridge',
      website: 'https://devpost.com/software/greenfridge',
      skill: ['React', 'Flask', 'GCP', 'Python', 'AI/ML', 'Back-end'],
      overview: "Fridge camera and accompanying app that reminds you what is in your fridge, and what is going to go bad, and fridge power usage",
      screens: '/assets/images/greenfridge.jpg',
      tech:`Raspberry pi, twilio`, 
    },
    pattrn: {
      image: '/assets/images/pattrns.gif',
      title: 'Pattrn',
      tagline: 'Turning wearables data into actionable insights',
      slug: 'pattrn',
      github: 'https://devpost.com/software/health-report-card',
      website: 'https://devpost.com/software/health-report-card',
      skill: ['React', 'Flask', 'AI/ML', 'Front-end'],
      overview: "Digests activity monitor data and produces bullet point actionable summary on health status, comparison against goals, and personalized recommendations",
      screens: '/assets/images/pattrns.gif',
      tech:`React, responsive design`, 
    },
    quinahealth: {
      image: '/assets/images/quina.jpg',
      title: 'Quina Health',
      tagline: 'Patient journey startup demo app and website',
      slug: 'quinahealth',
      github: 'https://quinahealth.com/',
      website: 'https://quinahealth.com/',
      skill: ['React', 'Django', 'AWS', 'Front-end'],
      overview: "Built their landing page, demo app including dashboard to visualize patient health history, and to do app to track patient journey",
      screens: '/assets/images/quina.jpg',
      tech:`AWS S3, EC2, Elastic Beanstalk, Route 53`, 
    },
  };

export default ProjectData;
  