const ProjectData = {
  mckinsey: {
    image: '/assets/images/mckinsey.png',
    title: 'Fellow Recruiting Platform for EDF',
    tagline: 'Selected as best project by EDF in McKinsey Hackathon',
    slug: 'mckinsey',
    github: 'https://github.com/Janecching/',
    website: 'https://github.com/Janecching/',
    skill: ['All','JavaScript', 'Full-stack', 'AI/LLM'],
    overview: "Built frontend of web app using JavaScript, HTML, CSS and proposed pipeline redesign for potential efficiency improvement of 89%",
    screens: '/assets/images/mckinsey.png',
    tech:`JavaScript, HTML, CSS, Node, Python, SQL, LLM (OpenAI)`, 
  },
  talenthunt: {
    image: '/assets/images/talenthunt.gif',
    title: 'AI Video Interview Platform',
    tagline: 'Top 10 project out of 1300 participants in UC Berkeley AI/LLM Hack',
    slug: 'talenthunt',
    github: 'https://github.com/srikrishna98/Tal-Hunt',
    website: 'https://github.com/srikrishna98/Tal-Hunt',
    skill: ['All', 'Full-stack', 'AI/LLM', 'JavaScript'],
    overview: "Automated candidate screening tool that uses LLM to generate personalized interview questions and evaluate candidate responses.",
    screens: '/assets/images/talenthunt.gif',
    tech:`React, Flask, Celery, (Speech to Text) Azure, LLM(OpenAI, LangChain, MindsDB), ML(Hume)`, 
  },
    frenchtutor: {
      image: '/assets/images/frenchtutor.gif',
      title: 'Conversational AI Language Tutor',
      tagline: "World's most patient and personalized language tutor",
      slug: 'frenchtutor',
      github: 'https://github.com/Janecching/french-tutor',
      website: 'https://github.com/Janecching/french-tutor',
      skill: ['All', 'AI/LLM', 'Full-stack', 'JavaScript'],
      overview: "Language learning web app that enhances conversation skills through simulated scenarios and offers sentence translation and correction for practice.",
      screens: '/assets/images/frenchtutor.gif',
      tech:`LLM (OpenAI), Node, JavaScript, HTML, CSS`, 
    },
    gooddays: {
      image: '/assets/images/gooddays.gif',
      title: 'AI Powered Journal',
      tagline: 'Let AI plan your daily schedule, and talk to your journal to learn about yourself',
      slug: 'gooddays',
      github: 'https://github.com/Janecching/one-day',
      website: 'https://one-hymvp2nzb-janecching.vercel.app/',
      skill: ['All', 'AI/LLM', 'Full-stack', 'JavaScript'],
      overview: `Turns braindump into daily calendar, talk to your journal to learn what makes you happy`,
      screens: '/assets/images/gooddays.gif',
      tech:`LLM (OpenAI, LangChain), Node, JavaScript, HTML, CSS`, 
    },
    discoveryqueue: {
      image: '/assets/images/dq.gif',
      title: 'Discovery Queue',
      tagline: "Find songs similar to your favourite song",
      slug: 'discoveryqueue',
      github: 'https://discoverq-83c0b.web.app/',
      website: 'https://discoverq-83c0b.web.app/',
      skill: ['All', 'Full-stack', 'Python'],
      overview: "Search new songs via a buzzfeed style quiz, filtering for music attributes, and most similar song based on cosine similarity",
      screens: '/assets/images/dq.gif',
      tech:`React, Node, Express, AWS RDS, MySQL, Python, ML (Cosine Similarity)`, 
    },
    virtualcampus: {
      image: '/assets/images/virtualcampus.gif',
      title: 'Virtual Campus',
      tagline: 'Online space for my masters program (MosaHacks Winner)',
      slug: 'virtualcampus',
      github: 'https://devpost.com/software/virtual-campus-1ra9fq',
      website: 'https://school-18507.web.app/social.html',
      skill: ['All','Full-stack', 'JavaScript'],
      overview: "This is a virtual campus made for my masters program community. It consists of a campus ground with live chat view and a focus room with pomodoro timer",
      screens: '/assets/images/virtualcampus.gif',
      tech:`Google Firebase, React, JavaScript`, 
    },
    greenfridge: {
      image: '/assets/images/greenfridge.gif',
      title: 'Green Fridge',
      tagline: "Know what's in your fridge (PennApps Winner)",
      slug: 'greenfridge',
      github: 'https://devpost.com/software/greenfridge',
      website: 'https://devpost.com/software/greenfridge',
      skill: ['All','Full-stack', 'ML'],
      overview: "Fridge camera and accompanying app that reminds you what is in your fridge, and what is going to go bad, and fridge power usage",
      screens: '/assets/images/greenfridge.gif',
      tech:`React, Flask, Google Cloud, Raspberry pi, Twilio`, 
    },
    pattrn: {
      image: '/assets/images/pattrns.gif',
      title: 'Pattrn',
      tagline: 'Turn your watch data into actionable insights (CalHacks Winner)',
      slug: 'pattrn',
      github: 'https://devpost.com/software/health-report-card',
      website: 'https://devpost.com/software/health-report-card',
      skill: ['All','Full-stack', 'Python'],
      overview: "Digests activity monitor data and produces bullet point actionable summary on health status, comparison against goals, and personalized recommendations",
      screens: '/assets/images/pattrns.gif',
      tech:`React, Flask, Cohere, CockroachDB, Google Cloud, Intersystems`, 
    },
    vaccine: {
      image: '/assets/images/Vaccine.jpg',
      title: 'Vaccination Tracker',
      tagline: 'Interactive program to query daily covid data for Philadelphia zipcodes',
      slug: 'vaccine',
      github: 'https://github.com/Janecching/',
      website: 'https://github.com/Janecching/',
      skill: ['All','Java'],
      overview: "Interactive program to query daily covid data for Philadelphia zipcodes",
      screens: '/assets/images/pattrns.gif',
      tech:`Java, Eclipse, JUnit`, 
    },
    battleship: {
      image: '/assets/images/Battleship.jpg',
      title: 'Battleship Game',
      tagline: 'Battleship game implemented from scratch in Java',
      slug: 'battleship',
      github: 'https://github.com/Janecching/',
      website: 'https://github.com/Janecching/',
      skill: ['All','Java'],
      overview: "Battleship game implemented from scratch in Java",
      screens: '/assets/images/Battleship.jpg',
      tech:`Java, Eclipse, JUnit`, 
    },
    student: {
      image: '/assets/images/Student.jpg',
      title: 'Student Management System',
      tagline: 'Student Management System',
      slug: 'student',
      github: 'https://github.com/Janecching/',
      website: 'https://github.com/Janecching/',
      skill: ['All','Java'],
      overview: "Student Management System",
      screens: '/assets/images/Student.jpg',
      tech:`Java, Eclipse, JUnit`, 
    },
    search: {
      image:  '/assets/images/search.jpg',
      title: 'Distributed Search Engine',
      tagline: 'Distributed Search Engine',
      slug: 'search',
      github: 'https://github.com/Janecching/',
      website: 'https://github.com/Janecching/',
      skill: ['All','Java'],
      overview: "Distributed Search Engine",
      screens:  '/assets/images/search.jpg',
      tech:`Java, JUnit`, 
    },
    assembler: {
      image: '/assets/images/assembler.jpg',
      title: 'Assembler - Disassembler',
      tagline: 'Developed C libraries to translate assembly language to binary files and back',
      slug: 'assembler',
      github: 'https://github.com/Janecching/',
      website: 'https://github.com/Janecching/',
      skill: ['All','C'],
      overview: "Developed C libraries to translate assembly language to binary files and back",
      screens: '/assets/images/assembler.jpg',
      tech:`C`, 
    },
    server: {
      image: '/assets/images/server.jpg',
      title: 'Shell, Client and Server in C',
      tagline: 'Shell program, TCP client and server in C',
      slug: 'server',
      github: 'https://github.com/Janecching/',
      website: 'https://github.com/Janecching/',
      skill: ['All','C'],
      overview: "Implemented a shell program, TCP client and server in C from scratch",
      screens: '/assets/images/server.jpg',
      tech:`C`, 
    },
    
    
  };

export default ProjectData;
  