const ProjectData = {
    frenchteacher: {
      image: '/assets/images/frenchteacher.jpg',
      title: 'AI French Teacher',
      tagline: "World's most patient language partner",
      slug: 'frenchteacher',
      github: 'https://github.com/Janecching',
      website: 'https://github.com/Janecching',
      skill: ['JavaScript', 'Node', 'OpenAI', 'AI/ML', 'Full-stack'],
      overview: "Language learning web app that enhances conversation skills through simulated scenarios and offers sentence translation and correction for practice.",
      screens: '/assets/images/frenchteacher.jpg',
      tech:`Web development (React, Next, Node, Express, OpenAI), UI/UX design, API integration, prompt engineering, language learning principles`, 
    },
    personalassistant: {
      image: '/assets/images/personalassistant.jpg',
      title: 'AI Personal Assistant',
      tagline: 'Clear your mind and focus on what matters',
      slug: 'personalassistant',
      github: 'https://github.com/Janecching',
      website: 'https://github.com/Janecching',
      skill: ['JavaScript', 'Node', 'OpenAI', 'AI/ML', 'Full-stack'],
      overview: "Productivity webapp that organizes and visualizes your chaotic mind into structured daily calendar ",
      screens: '/assets/images/personalassistant.jpg',
      tech:`Web development (React, Next, Node.js, Express, OpenAI), UI/UX design, API integration, natural language processing`, 
    },
    discoveryqueue: {
      image: '/assets/images/discoveryqueue.jpg',
      title: 'Discovery Queue',
      tagline: 'Discover your new favourite song',
      slug: 'discoveryqueue',
      github: 'https://discoverq-83c0b.web.app/',
      website: 'https://discoverq-83c0b.web.app/',
      skill: ['React', 'Node', 'AWS', 'Python', 'AI/ML', 'Full-stack'],
      overview: "Find new songs based on your current favourite song, buzzfeed style quiz, and search songs based on music attributes",
      screens: '/assets/images/discoveryqueue.jpg',
      tech:`Databases`, 
    },
    virtualcampus: {
      image: '/assets/images/virtualcampus.jpg',
      title: 'Virtual Campus',
      tagline: 'Virtual campus for my masters community',
      slug: 'virtualcampus',
      github: 'https://devpost.com/software/virtual-campus-1ra9fq',
      website: 'https://devpost.com/software/virtual-campus-1ra9fq',
      skill: ['React', 'JavaScript', 'GCP', 'Front-end'],
      overview: "This is a virtual campus made for my masters program community. It consists of a campus ground with live chat view and a focus room with pomodoro timer",
      screens: '/assets/images/virtualcampus.jpg',
      tech:`Javascript, real time multiplayer game`, 
    },
    greenfridge: {
      image: '/assets/images/greenfridge.jpg',
      title: 'Green Fridge',
      tagline: 'Fridge camera and accompanying app',
      slug: 'greenfridge',
      github: 'https://devpost.com/software/greenfridge',
      website: 'https://devpost.com/software/greenfridge',
      skill: ['React', 'Flask', 'GCP', 'Python', 'AI/ML', 'Back-end'],
      overview: "Fridge camera and accompanying app that reminds you what is in your fridge, and what is going to go bad, and fridge power usage",
      screens: '/assets/images/greenfridge.jpg',
      tech:`Raspberry pi, twilio`, 
    },
    pattrn: {
      image: '/assets/images/pattern.jpg',
      title: 'Pattrn',
      tagline: 'Turning wearables data into actionable insights',
      slug: 'pattrn',
      github: 'https://devpost.com/software/health-report-card',
      website: 'https://devpost.com/software/health-report-card',
      skill: ['React', 'Flask', 'AI/ML', 'Front-end'],
      overview: "Digests activity monitor data and produces bullet point actionable summary on health status, comparison against goals, and personalized recommendations",
      screens: '/assets/images/pattern.jpg',
      tech:`React, responsive design`, 
    },
    quinahealth: {
      image: '/assets/images/quina.jpg',
      title: 'Quina Health',
      tagline: 'Patient journey startup demo app and website',
      slug: 'quinahealth',
      github: 'https://quinahealth.com/',
      website: 'https://quinahealth.com/',
      skill: ['React', 'Django', 'AWS', 'Front-end'],
      overview: "Built their landing page, demo app including dashboard to visualize patient health history, and to do app to track patient journey",
      screens: '/assets/images/quina.jpg',
      tech:`AWS S3, EC2, Elastic Beanstalk, Route 53`, 
    },
  };

export default ProjectData;
  